USE [master]
GO
/****** Object:  Database [ProductDB]    Script Date: 09-08-2024 17:16:12 ******/
CREATE DATABASE [ProductDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProductDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProductDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ProductDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProductDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProductDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProductDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProductDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProductDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProductDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProductDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProductDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProductDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProductDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProductDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProductDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProductDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProductDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProductDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ProductDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProductDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProductDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProductDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProductDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProductDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ProductDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProductDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ProductDB] SET  MULTI_USER 
GO
ALTER DATABASE [ProductDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProductDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProductDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProductDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProductDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProductDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProductDB', N'ON'
GO
ALTER DATABASE [ProductDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [ProductDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ProductDB]
GO
/****** Object:  Table [dbo].[Product_Details]    Script Date: 09-08-2024 17:16:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product_Details](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [varchar](200) NULL,
	[Size] [char](1) NULL,
	[Price] [float] NULL,
	[MfgDate] [datetime] NULL,
	[Category] [varchar](50) NULL,
 CONSTRAINT [PK_Product_Details] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Product_Details] ON 
GO
INSERT [dbo].[Product_Details] ([ProductID], [ProductName], [Size], [Price], [MfgDate], [Category]) VALUES (1, N'Glasses', N'S', 100, CAST(N'2024-08-09T00:00:00.000' AS DateTime), N'Standard')
GO
INSERT [dbo].[Product_Details] ([ProductID], [ProductName], [Size], [Price], [MfgDate], [Category]) VALUES (2, N'Furniture', N'M', 200, CAST(N'2024-07-06T00:00:00.000' AS DateTime), N'Premium')
GO
SET IDENTITY_INSERT [dbo].[Product_Details] OFF
GO
/****** Object:  StoredProcedure [dbo].[ProductSearch]    Script Date: 09-08-2024 17:16:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[ProductSearch]       
 @ProductName varchar(250)
	, @Size char(1) 
	, @Price float
	, @MfgDate varchar(250)
	,@Category varchar(20)
as
begin

select ProductID,ProductName,Size,Price,MfgDate,Category from Product_Details where 
1=(Case when ISNULL(@ProductName,'')='' THEN 1
WHEN ISNULL(@ProductName,'') <> '' AND ProductName=@ProductName then 1
ELSE 0 end)
AND 
1=(Case when ISNULL(@Size,'')='' THEN 1
WHEN ISNULL(@Size,'') <> '' AND Size=@Size then 1
ELSE 0 end)
AND 
1=(Case when ISNULL(@Price,'')='' THEN 1
WHEN ISNULL(@Price,'') <> '' AND Price=@Price then 1
ELSE 0 end)
AND 
1=(Case when ISNULL(@MfgDate,'')='' THEN 1
WHEN ISNULL(@MfgDate,'') <> '' AND CONVERT(DATE,MfgDate)=@MfgDate then 1
ELSE 0 end)
AND 
1=(Case when ISNULL(@Category,'')='' THEN 1
WHEN ISNULL(@Category,'') <> '' AND Category=@Category then 1
ELSE 0 end)

end

GO
USE [master]
GO
ALTER DATABASE [ProductDB] SET  READ_WRITE 
GO
